# Generated by Django 3.1.4 on 2020-12-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0002_auto_20201219_0923"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="belarus_bank_code",
            field=models.CharField(
                default=None, max_length=50, verbose_name="Belarusbank Code"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
    ]
