version: '1'
services:
  postgres:
    image: postgres:latest
    env_file: .env
    volumes:
      - exchange_aggregator_database:/var/lib/postgresql/data
    ports:
      - 5432:5432
  rabbitmq:
    image: library/rabbitmq:latest
    env_file: .env
    volumes:
      - broker:/etc/rabbitmq/
      - broker:/var/lib/rabbitmq/
      - broker:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: library/redis:latest
    env_file: .env
    command: "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
    ports:
      - 6379:6379


volumes:
  storage:
  exchange_aggregator_database:
  broker:
