version: '3'
services:
  postgres:
    image: postgres:latest
    env_file: .env
    volumes:
      - exchange_aggregator_database:/var/lib/postgresql/data
    ports:
      - 5432:5432
  rabbitmq:
    image: library/rabbitmq:latest
    env_file: .env
    volumes:
      - broker:/etc/rabbitmq/
      - broker:/var/lib/rabbitmq/
      - broker:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
  app:
    build: .
    env_file: .env
    command: prod
    volumes:
      - .:/app
      - storage:/app/storage
    depends_on:
      - postgres
    ports:
      - 8000:8000

  celery_app:
    build: .
    env_file: .env
    command: celery
    volumes:
      - .:/app
      - storage:/app/storage
    depends_on:
      - rabbitmq

volumes:
  storage:
  exchange_aggregator_database:
  broker:
